version: '3'
services:
  web69:
    environment:
      - ROOT_DIR=/app/web/
      - PORT=:6969
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "6969:6969"
    restart: always
  web70:
    environment:
      - ROOT_DIR=/app/web/
      - PORT=:6970
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "6970:6970"
    restart: always
  web71:
    environment:
      - ROOT_DIR=/app/web/
      - PORT=:6971
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "6971:6971"
    restart: always
  lb:
    environment:
      - ROOT_DIR=/app/lb/
      - PORT=:7070
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "7070:7070"
    depends_on:
      - web69
      - web70
      - web71
    restart: always
