ARG GO_VERSION=1.22
FROM golang:${GO_VERSION}-alpine AS build

WORKDIR /app

ENV GO111MODULE=on
ENV ROOT_DIR="/app"

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o lbbinary ./lb

CMD ["./lbbinary"]
